config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  root to: 'tasks#index'
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  validates :title, presence: true
  validates :content, presence: true
  validates :start_time, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_post, only: %i[edit update destroy]

  def index
    @tasks = Task.where(user_id: current_user.id).includes(:user)
    @task = current_user.tasks.build
  end

  def new
    @task = Task.new
  end

  def show
    @task = Task.find(params[:id])
  end

  def create
    @task = current_user.tasks.create(task_params)
    redirect_to tasks_path, notice: '登録しました'
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path, notice: '削除しました'
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update!(task_params)
      redirect_to tasks_path, notice: '編集しました'
    else
      render 'edit'
    end
  end

  private

  def task_params
    params.require(:task).permit(:title, :content, :start_time)
  end

  def set_post
    @task = current_user.tasks.find(params[:id])
    redirect_to tasks_path, notice: '権限がありません' if @task.nil?
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  before_action :ensure_normal_user, only: :create

  def ensure_normal_user
    if params[:user][:email].downcase == 'guest@example.com'
      redirect_to new_user_session_path, notice: 'ゲストユーザーのパスワード再設定はできません。'
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :ensure_normal_user, only: %i[update destroy]

  def ensure_normal_user
    redirect_to root_path, notice: 'ゲストユーザーの編集・削除できません。' if resource.email == 'guest@example.com'
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    sign_in User.guest
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
    #task_path?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def max_width
    if controller_name == 'tasks' && action_name == 'show'
      'mw-md'
    elsif devise_controller?
      'mw-sm'
    else
      'mw-xl'
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Tasks App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'shared/header' %>
    <% flash.each do |flash_type, msg| %>
      <p><%= msg %></p>
    <% end %>
    <hr>
    <%= yield %>
  </body>
</html>

app/views/shared/_header.html.erb
<header class="sticky-top">
  <nav class="navbar navbar-expand-sm navbar-light bg-light">
    <%= link_to "My Tasks App", root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "アカウント編集", edit_user_registration_path, class: "nav-link active" %>
          </li>
          <li class="nav-item">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, data: { confirm: "ログアウトしますか？" }, class: "nav-link active" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "新規登録", new_user_registration_path, class: "nav-link active" %>
          </li>
          <li class="nav-item">
            <%= link_to "ログイン", new_user_session_path, class: "nav-link active" %>
          </li>
          <li class="nav-item">
            <%= link_to "ゲストログイン（閲覧用）", users_guest_sign_in_path, class: "nav-link active", method: :post %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js" integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em" crossorigin="anonymous"></script>
</header>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/tasks/edit.html.erb
<%= form_with(model: @task, local: true) do |form| %>
  <div class="title">
    <div class="form-tag">タイトル</div>
    <%= form.text_field :title %>
  </div>
  <div class="content">
    <div class="form-tag">内容</div>
    <%= form.text_field :content %>
  </div>
  <div class="time">
    <div class="form-tag">日程</div>
    <%= form.date_select :start_time %>
  </div>
  <div class="submit">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/index.html.erb
<!--<p id="notice"><%= notice %></p>-->
<div class="toppage">
  <% if user_signed_in? %>
    <li class="top"><%= "#{current_user.email}でログイン中" %></li>
  <% end %>
  <br>
  <div class="row">
    <div class="col-md-4">
      <div class="schedule">
        <h2>予定一覧</h2>
      </div>
      <table class="table">
        <thead class="thead-light">
          <tr>
            <th>タイトル</th>
            <th>日程</th>
          </tr>
        </thead>
        <tbody>
          <% @tasks.each do |task| %>
            <tr>
              <td><%= link_to task.title , task %></td>
              <td><%= task.start_time.strftime("%m月%d日") %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= form_with(model: @task, local: true) do |form| %>
        <div class="title">
          <div class="form-tag">タイトル</div>
          <%= form.text_field :title %>
        </div>
        <div class="content">
          <div class="form-tag">内容</div>
          <%= form.text_field :content %>
        </div>
        <div class="time">
          <div class="form-tag">日程</div>
          <%= form.date_select :start_time %>
        </div>
        <div class="submit">
          <%= form.submit %>
        </div>
      <% end %>
    </div>
    <br>
    <br>
    <div class="col-md-8">
      <%= month_calendar events: @tasks do |date, tasks| %>
        <%= date.day %>
        <% tasks.each do |task| %>
          <div>
            <%= link_to task.title, task %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>
<div class="show">
  <% if current_user.id == @task.user_id %>
    <p>
      <strong>タイトル</strong>
      <%= simple_format(h @task.title) %>
    </p>
    <p>
      <strong>内容</strong>
      <%= simple_format(h @task.content) %>
    </p>
    <p>
      <strong>日時</strong>
      <%= @task.start_time.strftime("%m月%d日") %>
    </p>
    <%= link_to '編集', edit_task_path(@task) %>
    <%= link_to '削除', task_path(@task.id), method: :delete, data: { confirm: '削除しますか?' } %>
    <%= link_to '戻る', tasks_path %>
  <% end %>
</div>